### PR TITLE
Spherical joint implementation

### PR DESCRIPTION
**Pull request by PaulSchreiner**
Here is the first version of the spherical joint implementation. 

- I chose to implement the spherical joint using quaternions for numerical stability, avoiding to have time dependent joints as well as consistency with floating base.

- For the multi dimensional case of the joint subspace S I created a tiny_matrix6x3 struct now, I am still considering to use vectors of motion vectors instead so it can be generalized for any dimension. This would entail creating a struct for S as is done in RBDL.

- CMakeLists.txt
  - added target for spherical_joint_test.cpp

- Added spherical_joint_test.cpp and pendulum_spherical_joints.hpp

- forward_dynamics.hpp:
  - Added switches for spherical joints

- integrator.hpp
  - added switch for spherical joints, implementing integration in the same way as the floating base is done

- kinematics.hpp
  - Changed type q and qd to VectorX

- mass_matrix.hpp:
  - Added switch for spherical joints, is not updating for parents yet!

- link.hpp: 
  - added a case to set_joint_type()
  - added 3 dimensional versions of the temp variables (U, D and u) as well as invD to avoid redundant recalculation of the matrix inverse
  - created VectorX versions of Link::jcalc() and added cases for the spherical joint

- inertia.hpp:
  - Overloaded operator* for matrix6x3
  - Created a mul_transpose method for transpose multiplications of 2 matrix6x3 to form a 6x6 matrix in abi format.

- spatial_vector.hpp:
  - Overloaded some necessary operators to be able to multiply between matrix6x3 and motion/force vectors

- tiny_algebra.hpp:
  - added methods to multiply matrix6x3 with vector3, returning motion or force vectors
  - added quaternion to angle and quaternion to axis-angle methods

- tiny_matrix6x3.hpp:
  - implemented a 6x3 matrix struct in a similar way as how the 6x6 matrix is implemented

- multi_body.hpp:
  - Created a shperical joint counter member + getter method, to account for the discrepancy between DoF's and size of q
  - Added switches to initialize() and attach() methods
  - Converted getters for joint-coordinates, -velocities, -torques and -accelerations to return VectorX's with size depending on the joint type

Like I wrote in my mail, there seems to be an issue with the implementation still. The simulation gets unstable for certain initial conditions or when there is more than a few links attached, I am not sure the two are related.

The initial condition case:
I have been looking at what the bug can be and at first I thought it might be an issue with the inertia matrix but I couldn't  find an error in the implemented logic. 
Then I thought it might have to do with how I initialized the joint. I initialized it exactly the same way as in the pendulum experiment: Initializing the joints with the center of mass at a pure y-axis position. Then having the initial quaternions as q0=[0,0,0,1] the simulation runs as expected. However, setting q0=[0,0,sqrt(1/2), sqrt(1/2)] renders it unstable. However, when I initialize it as having its CoM in the pure (-) z direction I can initialize using q0=[sqrt(1/2), 0, 0, sqrt(1/2)] and q0=[0,sqrt(1/2),0, sqrt(1/2)] and the simulation runs fine in both cases.

Still when initializing with more than ~7/8 spherical joints chained together renders the simulation unstable very quickly, I am wondering if this could be an integrator issue, i.e. that euler steps are not enough?

I will have a look at how RBDL does this for spherical joints.

### CODE REVIEW

**Comment by PaulSchreiner** [comment]
@googlebot I signed it!

 
Paul Schreiner
Industrial PhD Student
 
Rokoko.com <http://www.rokoko.com/>

**Comment by PaulSchreiner** [comment]
@googlebot I signed it!

**Comment by erwincoumans** [comment]
Thanks Paul. Are all the commits using the github email address that you registered, and the same email address for the CLA?

You could also try to create a new fork, using latest master, and re-apply the changes in a single commit making sure the email address is OK? 

Also, travis compilation fails, can you check the output of travis?
https://travis-ci.org/github/google-research/tiny-differentiable-simulator/builds/747393175

**Comment by PaulSchreiner** [comment]
Hi Erwin, 

Sorry that I haven’t had the time to reply earlier.

I received a mail that there was an issue with my title, I can’t sign the CLA, it should be signed by an executive. That has now been done, so I am waiting for it to be approved by google now.

Best,


 
Paul Schreiner
Industrial PhD Student
 
Rokoko.com <http://www.rokoko.com/>

**Comment by PaulSchreiner** [comment]
I am closing this, since it needs some unforseen implementation. I had not counted with the "EigenAlgebra" and the implications that has for the Matrix6x3 struct I made. I have been using the member functions of some of the Tiny structs instead of using the Algebra:: methods.

I'll change this and make a new PR when that is done.

**Pull request closed without merging**
