### PR TITLE
Add Laikago whole body control example

### PR DESCRIPTION
**Pull request by AiRuiChen**
Added a cpp version of laikago whole body control example. (python version is [here](https://github.com/google-research/tiny-differentiable-simulator/tree/master/python/examples/whole_body_control))

A TDS network can now be constructed with a json file with neural network parameters. Thus, we can load a neural network's params to a json file in python, and use the same model in tds.

### CODE REVIEW

**Comment by eric-heiden** [comment]
@googlebot I consent.

**Comment by erwincoumans** [comment]
Thanks for the contribution. Quick note: Please don't use 
include_directories(tds/third_party/nlohmann/include)
best to have the example/demo load the data, and convert it to generic data (std::vector or Algebra:: types etc) and then pass that to the neural network.
The src folder should not be come dependent on a json header.
Also, in general use target_include_directories instead of include_directories.

**Comment by AiRuiChen** [comment]
> Thanks for the contribution. Quick note: Please don't use
> include_directories(tds/third_party/nlohmann/include)
> best to have the example/demo load the data, and convert it to generic data (std::vector or Algebra:: types etc) and then pass that to the neural network.
> The src folder should not be come dependent on a json header.
> Also, in general use target_include_directories instead of include_directories.

I see. One concern is we might want to add a `dump()` functionality for `tds::NeuralNetwork` in order to save a trained model. We'd probably still rely on json as the output format as it is cross platform and easy to serialize to disk.  Json dependency sounds mandatory if we want this.

Can we add a cmake option `USE_JSON` and include the json header conditionally?

**Comment by erwincoumans** [comment]
Haven't looked at the details yet. We can have the load and save methods in a derived class (which can depend on json), and store that class somewhere outside of src, such as in the examples directory?

Also, please don't use include_directories, always use target_include_directories for a specific target.

**Comment by AiRuiChen** [comment]
> Haven't looked at the details yet. We can have the load and save methods in a derived class (which can depend on json), and store that class somewhere outside of src, such as in the examples directory?
> 
> Also, please don't use include_directories, always use target_include_directories for a specific target.

Done. Please take a look at the updated code.

**Comment by erwincoumans** [comment]
Thanks. There are a few nits that I'll fix after merging:

~~~~~~~
  int secs_since_start;
  while (secs_since_start < TOTAL_SECS) {
~~~~~~~
Initialize secs_since_start to 0 before using it (in comparison).

Move mpc_ffn_model.json to the data folder, and use this code (instead of argv[1]:
~~~~~~~~~~~~~~
std::string nn_json_filename;
  tds::FileUtils::find_file("mpc_ffn_model.json",
                            nn_json_filename);
~~~~~~~~~~~~~~

**Pull request merged**
