### PR TITLE
added OpenGl viewer example in python

### PR DESCRIPTION
**Pull request by vittorione94**
Python example that uses OpenGL visualizer.
The example loads the Laikago model, simulate physics with gravity and collides with the floor.

### CODE REVIEW

**Comment by vittorione94** [comment]
@googlebot I signed it!

**Comment by erwincoumans** [comment]
Thanks for the contribution. What do the changes to C++, get_sim_state and pause/reset sim etc do? If they just store state, can it be done in Python? Did we expose keyboard events in Python?

**Comment by vittorione94** [comment]
Thanks for the reply :) you're totally right get_sim_state is just storing a state. I think it would be much neater done in Python, like checking if the key has been pressed instead of querying the window for the current state. However, I don't think keyboard events have been exposed in Python and I'm not sure what would be the best way of exposing them.

**Comment by erwincoumans** [comment]
closing for now, will consider exposing better UI capabilities in a different way.

**Pull request closed without merging**
