### PR TITLE
WIP: fix rotated inertia

### PR DESCRIPTION
**Pull request by eric-heiden**
This PR fixes a bug when applying a rotation to inertia matrices defined in the URDF file.
WIP on correcting the floating-base case for the ant leg.

### CODE REVIEW

**Comment by eric-heiden** [comment]
@googlebot I signed it!

**Comment by erwincoumans** [comment]
Thanks a lot Eric. It looks like the new tests don't pass in CI?

**Comment by eric-heiden** [comment]
I forgot to commit my changes to test_rbdl so that a random base transform is only set for the tests of floating-base and not fixed-base systems.

**Comment by erwincoumans** [comment]
Thanks for the contribution, LGTM.

**Pull request merged**
